name: Linter
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
